title: Linebreakers
description: "Specs, bugs, and rock'n'roll"
theme: just-the-docs
color_scheme: dark

url: https://linebreakers.band

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

collections:
    people:
        output: true
